### ISSUE TITLE
Marathon service restarted always (even for unchanged config)

### ISSUE THREAD

**Issue by lhoss** [AnsibleShipyard/ansible-marathon#29]
I propose to split following task into 1 task to `enable` the service and one that restarts it (through a handler):
```
- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes
  tags:
    - restart
```
